version: '3.8'

services:
  react-app:
    build:
      context: . ###assuming docker file is present in cuurent dir
    container_name: react-app
    ports:
      - "8082:80"   #exposes react development server on port 80
    volumes:
      - ./src:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm","start"]
    


